#!/bin/python3

import sys
import math

first,last = input().strip().split(' ')
first,last = [int(first),int(last)]
# your code goes here
primelist = []
megalist = []
for i in range(first,last+1):
    prime = True
    for j in range(2,int(math.sqrt(i)+1)):
        if i%j == 0:
            prime = False
    if i in range(0,2):
        continue
    elif i == 2:
        primelist.append(i)
    elif prime == True:
        primelist.append(i)

for i in primelist:
    if i in (2,3,5,7):
        megalist.append(i)
    else:
        n = i
        megaprimeflag = True
        while n > 0:
            r = n%10
            if r == 1:
                megaprimeflag = False
                n=0 
            for k in range(2,int(math.sqrt(r)+1)):
                if r%k == 0:
                    megaprimeflag = False
            n = int(n/10)
        if megaprimeflag == True:
            megalist.append(i)
print (len(megalist))
